In [2]:
import xarray as xr
import schwabdev as sd
import json
import numpy as np
import pandas as pd
from datetime import datetime, date, timedelta, time
import calendar
import time as tm

from universes.universe_config import Universe_Config as uc

def create_client():
    """Create a Schwab client with API keys."""
    with open('keys.json', 'r') as f:
        keys = json.load(f)

    return sd.Client(keys['schwab']['app_key'], keys['schwab']['app_secret'])

client = create_client()

Exception in thread Thread-5 (checker):
Traceback (most recent call last):
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/socket.py", line 977, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
                       ~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f13c0f7ae90>: Failed to resolve 'api.schwabapi.com' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.schwabapi.com', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f13c0f7ae90>: Failed to resolve 'api.schwabapi.com' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/client.py", line 47, in checker
    if self.tokens.update_tokens() and use_session:
       ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 177, in update_tokens
    self.update_access_token()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 190, in update_access_token
    response = self._post_oauth_token('refresh_token', self.refresh_token)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 112, in _post_oauth_token
    return requests.post('https://api.schwabapi.com/v1/oauth/token', headers=headers, data=data)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.schwabapi.com', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f13c0f7ae90>: Failed to resolve 'api.schwabapi.com' ([Errno -3] Temporary failure in name resolution)"))

In [19]:
quotes_10 = []
for i in range(10):
    quotes_10.append(uc.return_universe_quotes("u01"))
    print(i)
    tm.sleep(60)

0
1
2
3
4
5
6
7
8
9

Exception in thread Thread-10 (checker):
Traceback (most recent call last):
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/socket.py", line 977, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
                       ~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f13c0f7afd0>: Failed to resolve 'api.schwabapi.com' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.schwabapi.com', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f13c0f7afd0>: Failed to resolve 'api.schwabapi.com' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/client.py", line 47, in checker
    if self.tokens.update_tokens() and use_session:
       ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 177, in update_tokens
    self.update_access_token()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 190, in update_access_token
    response = self._post_oauth_token('refresh_token', self.refresh_token)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 112, in _post_oauth_token
    return requests.post('https://api.schwabapi.com/v1/oauth/token', headers=headers, data=data)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.schwabapi.com', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f13c0f7afd0>: Failed to resolve 'api.schwabapi.com' ([Errno -3] Temporary failure in name resolution)"))
Exception in thread Thread-12 (checker):
Traceback (most recent call last):
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/socket.py", line 977, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
                       ~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f13c0f7a990>: Failed to resolve 'api.schwabapi.com' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.schwabapi.com', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f13c0f7a990>: Failed to resolve 'api.schwabapi.com' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/client.py", line 47, in checker
    if self.tokens.update_tokens() and use_session:
       ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 177, in update_tokens
    self.update_access_token()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 190, in update_access_token
    response = self._post_oauth_token('refresh_token', self.refresh_token)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 112, in _post_oauth_token
    return requests.post('https://api.schwabapi.com/v1/oauth/token', headers=headers, data=data)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.schwabapi.com', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f13c0f7a990>: Failed to resolve 'api.schwabapi.com' ([Errno -3] Temporary failure in name resolution)"))
Exception in thread Thread-11 (checker):
Traceback (most recent call last):
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/socket.py", line 977, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
                       ~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f13c0f7ac10>: Failed to resolve 'api.schwabapi.com' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.schwabapi.com', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f13c0f7ac10>: Failed to resolve 'api.schwabapi.com' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/client.py", line 47, in checker
    if self.tokens.update_tokens() and use_session:
       ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 177, in update_tokens
    self.update_access_token()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 190, in update_access_token
    response = self._post_oauth_token('refresh_token', self.refresh_token)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 112, in _post_oauth_token
    return requests.post('https://api.schwabapi.com/v1/oauth/token', headers=headers, data=data)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.schwabapi.com', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f13c0f7ac10>: Failed to resolve 'api.schwabapi.com' ([Errno -3] Temporary failure in name resolution)"))
Exception in thread Thread-14 (checker):
Traceback (most recent call last):
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/socket.py", line 977, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The refresh token will expire soon! (12H:00M:17S remaining)
The refresh token will expire soon! (11H:45M:17S remaining)
The refresh token will expire soon! (11H:30M:16S remaining)
The refresh token will expire soon! (11H:15M:16S remaining)
The refresh token will expire soon! (11H:00M:15S remaining)
The refresh token will expire soon! (10H:45M:15S remaining)
The refresh token will expire soon! (10H:30M:15S remaining)
The refresh token will expire soon! (10H:15M:15S remaining)
The refresh token will expire soon! (10H:00M:14S remaining)
The refresh token will expire soon! (09H:45M:14S remaining)
The refresh token will expire soon! (09H:30M:13S remaining)
The refresh token will expire soon! (09H:15M:13S remaining)
The refresh token will expire soon! (09H:00M:13S remaining)
The refresh token will expire soon! (08H:45M:13S remaining)
The refresh token will expire soon! (08H:30M:12S remaining)
The refresh token will expire soon! (08H:15M:12S remaining)
The refresh token will expire soon! (08H:00M:11S remaining)
The refresh token will expire soon! (07H:45M:11S remaining)
The refresh token will expire soon! (07H:30M:10S remaining)
The refresh token will expire soon! (07H:15M:10S remaining)
The refresh token will expire soon! (07H:00M:10S remaining)
The refresh token will expire soon! (06H:45M:10S remaining)
The refresh token will expire soon! (06H:30M:09S remaining)
The refresh token will expire soon! (06H:15M:09S remaining)
The refresh token will expire soon! (06H:00M:08S remaining)
The refresh token will expire soon! (05H:45M:08S remaining)
The refresh token will expire soon! (05H:30M:07S remaining)
The refresh token will expire soon! (05H:15M:07S remaining)
The refresh token will expire soon! (05H:00M:07S remaining)
The refresh token will expire soon! (04H:45M:06S remaining)
The refresh token will expire soon! (04H:30M:06S remaining)
The refresh token will expire soon! (04H:15M:05S remaining)
The refresh token will expire soon! (04H:00M:05S remaining)
The refresh token will expire soon! (03H:45M:05S remaining)
The refresh token will expire soon! (03H:30M:05S remaining)
The refresh token will expire soon! (03H:15M:04S remaining)
The refresh token will expire soon! (03H:00M:04S remaining)
The refresh token will expire soon! (02H:45M:03S remaining)
The refresh token will expire soon! (02H:30M:03S remaining)
The refresh token will expire soon! (02H:15M:02S remaining)
The refresh token will expire soon! (02H:00M:02S remaining)
The refresh token will expire soon! (01H:45M:02S remaining)
The refresh token will expire soon! (01H:30M:02S remaining)
The refresh token will expire soon! (01H:15M:01S remaining)
The refresh token will expire soon! (01H:00M:01S remaining)
The refresh token will expire soon! (00H:45M:00S remaining)
The refresh token will expire soon! (00H:30M:00S remaining)

The refresh token has expired!

[Schwabdev] Open to authenticate: https://api.schwabapi.com/v1/oauth/authorize?client_id=H5LG9qEE9hv7uRy14FcWHdJMxCFdJWGa&redirect_uri=https://127.0.0.1
[Schwabdev] After authorizing, paste the address bar url here:

Exception in thread Thread-19 (checker):
Traceback (most recent call last):
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/willse/.pyenv/versions/3.13.5/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/client.py", line 47, in checker
    if self.tokens.update_tokens() and use_session:
       ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 172, in update_tokens
    self.update_refresh_token()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/willse/W_Projects/Quant_Trading/.venv/lib/python3.13/site-packages/schwabdev/tokens.py", line 358, in update_refresh_token
    response_url = input("[Schwabdev] After authorizing, paste the address bar url here: ")
EOFError: EOF when reading a line

In [57]:
q0 = quotes_10[0]
q0 = q0.set_index(['ident'])
q0.columns

Index(['assetMainType', 'assetSubType', 'quoteType', 'realtime', 'ssid',
       'symbol', 'extended.askPrice', 'extended.askSize', 'extended.bidPrice',
       'extended.bidSize', 'extended.lastPrice', 'extended.lastSize',
       'extended.mark', 'extended.quoteTime', 'extended.totalVolume',
       'extended.tradeTime', 'fundamental.avg10DaysVolume',
       'fundamental.avg1YearVolume', 'fundamental.divAmount',
       'fundamental.divFreq', 'fundamental.divPayAmount',
       'fundamental.divYield', 'fundamental.eps',
       'fundamental.fundLeverageFactor', 'fundamental.lastEarningsDate',
       'fundamental.peRatio', 'quote.52WeekHigh', 'quote.52WeekLow',
       'quote.askMICId', 'quote.askPrice', 'quote.askSize', 'quote.askTime',
       'quote.bidMICId', 'quote.bidPrice', 'quote.bidSize', 'quote.bidTime',
       'quote.closePrice', 'quote.highPrice', 'quote.lastMICId',
       'quote.lastPrice', 'quote.lastSize', 'quote.lowPrice', 'quote.mark',
       'quote.markChange', 'quote.markPercentChange', 'quote.netChange',
       'quote.netPercentChange', 'quote.openPrice', 'quote.postMarketChange',
       'quote.postMarketPercentChange', 'quote.quoteTime',
       'quote.securityStatus', 'quote.totalVolume', 'quote.tradeTime',
       'reference.cusip', 'reference.description', 'reference.exchange',
       'reference.exchangeName', 'reference.isHardToBorrow',
       'reference.isShortable', 'reference.htbQuantity', 'reference.htbRate',
       'regular.regularMarketLastPrice', 'regular.regularMarketLastSize',
       'regular.regularMarketNetChange', 'regular.regularMarketPercentChange',
       'regular.regularMarketTradeTime', 'fundamental.declarationDate',
       'fundamental.divExDate', 'fundamental.divPayDate',
       'fundamental.nextDivExDate', 'fundamental.nextDivPayDate',
       'reference.otcMarketTier', 'reference.fsiCode', 'reference.fsiDesc',
       'invalidSymbols'],
      dtype='object')

In [58]:
q0['quote.quoteTime'] = pd.to_datetime(q0['quote.quoteTime'], unit='ms', utc=True).map(lambda x: x.tz_convert("America/new_York"))
q0['quote.tradeTime'] = pd.to_datetime(q0['quote.tradeTime'], unit='ms', utc=True).map(lambda x: x.tz_convert("America/new_York"))
q0['quote.askTime'] = pd.to_datetime(q0['quote.askTime'], unit='ms', utc=True).map(lambda x: x.tz_convert("America/new_York"))
q0['quote.bidTime'] = pd.to_datetime(q0['quote.bidTime'], unit='ms', utc=True).map(lambda x: x.tz_convert("America/new_York"))
q0['regular.regularMarketTradeTime'] = pd.to_datetime(q0['regular.regularMarketTradeTime'], unit='ms', utc=True).map(lambda x: x.tz_convert("America/new_York"))

In [59]:
q0[['quote.totalVolume','quote.lastSize','quote.tradeTime','quote.askTime','quote.bidTime','quote.quoteTime']]

,quote.totalVolume,quote.lastSize,quote.tradeTime,quote.askTime,quote.bidTime,quote.quoteTime
ident,,,,,,
WBD,25303743.0,796.0,2025-07-30 13:11:59.479000-04:00,2025-07-30 13:11:59.481000-04:00,2025-07-30 13:11:59.481000-04:00,2025-07-30 13:11:59.481000-04:00
F,30492797.0,100.0,2025-07-30 13:11:58.979000-04:00,2025-07-30 13:11:51.108000-04:00,2025-07-30 13:11:58.254000-04:00,2025-07-30 13:11:58.254000-04:00
BBAI,28702471.0,200.0,2025-07-30 13:11:55.644000-04:00,2025-07-30 13:11:55.866000-04:00,2025-07-30 13:11:56.197000-04:00,2025-07-30 13:11:56.197000-04:00
PSLV,20398450.0,146.0,2025-07-30 13:11:52.759000-04:00,2025-07-30 13:11:55.085000-04:00,2025-07-30 13:11:53.056000-04:00,2025-07-30 13:11:55.085000-04:00
VALE,31018502.0,400.0,2025-07-30 13:11:59.356000-04:00,2025-07-30 13:11:56.278000-04:00,2025-07-30 13:11:56.278000-04:00,2025-07-30 13:11:56.278000-04:00
...,...,...,...,...,...,...
PBSFY,0.0,0.0,2025-07-18 13:20:50.197000-04:00,2025-07-30 12:08:29.873000-04:00,2025-07-30 11:32:11.605000-04:00,2025-07-30 12:08:29.873000-04:00
SMGBF,0.0,1000.0,2025-07-28 15:49:17.936000-04:00,2025-07-30 09:56:16.262000-04:00,2025-07-30 09:30:05.581000-04:00,2025-07-30 09:56:16.262000-04:00
SWRBF,0.0,100.0,2025-07-29 14:09:46.300000-04:00,2025-07-30 09:56:16.255000-04:00,2025-07-30 09:56:10.852000-04:00,2025-07-30 09:56:16.255000-04:00
CYGIY,0.0,20.0,2025-07-28 12:19:37.671000-04:00,2025-05-16 17:00:03.274000-04:00,2025-05-16 17:00:03.274000-04:00,2025-05-16 17:00:03.274000-04:00
SATLF,0.0,0.0,2025-07-22 09:30:17.434000-04:00,2025-07-30 07:20:34.956000-04:00,2025-07-30 07:03:05.847000-04:00,2025-07-30 07:20:34.956000-04:00

In [64]:
import matplotlib.pyplot as plt
q0[['quote.totalVolume','quote.lastSize','quote.tradeTime','quote.askTime','quote.securityStatus']][q0['quote.securityStatus'] != 'Normal'].sort_values(by='quote.tradeTime')

,quote.totalVolume,quote.lastSize,quote.tradeTime,quote.askTime,quote.securityStatus
ident,,,,,
errors,NaN,NaN,NaT,NaT,NaN
errors,NaN,NaN,NaT,NaT,NaN